"""Generate frontend/src/lib/api-types.gen.ts from the FastAPI OpenAPI schema.

Usage: .venv/bin/python scripts/generate_frontend_api_types.py [--check]

``--check`` exits non-zero when the committed file is out of date (the test
suite runs the same comparison).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend" / "src" / "lib" / "api-types.gen.ts"
HEADER = "// Generated by scripts/generate_frontend_api_types.py from the backend OpenAPI schema. Do not edit.\n"


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        members = list(dict.fromkeys(_ts_type(item) for item in schema["anyOf"]))
        return " | ".join(members)
    if "enum" in schema:
        return " | ".join(f'"{value}"' if isinstance(value, str) else str(value) for value in schema["enum"])
    if "const" in schema:
        value = schema["const"]
        return f'"{value}"' if isinstance(value, str) else str(value)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = _ts_type(schema.get("items", {}))
        return f"({item})[]" if "|" in item else f"{item}[]"
    if kind == "object" or "additionalProperties" in schema:
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict) and additional:
            return f"Record<string, {_ts_type(additional)}>"
        return "Record<string, unknown>"
    return "unknown"


def render(openapi: dict[str, Any]) -> str:
    lines = [HEADER]
    for name, schema in sorted(openapi["components"]["schemas"].items()):
        lines.append("")
        if "properties" not in schema:
            lines.append(f"export type {name} = {_ts_type(schema)};")
            continue
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for prop_name, prop_schema in schema["properties"].items():
            optional = "" if prop_name in required else "?"
            lines.append(f"  {prop_name}{optional}: {_ts_type(prop_schema)};")
        lines.append("}")
    return "\n".join(lines) + "\n"


def generate() -> str:
    sys.path.insert(0, str(ROOT / "src"))
    from book_agent.app.main import create_app

    return render(create_app().openapi())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run scripts/generate_frontend_api_types.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
