// Generated by scripts/generate_frontend_api_types.py from the backend OpenAPI schema. Do not edit.


export interface AgentTurnResponse {
  id: string;
  document_id: string;
  run_id?: string | null;
  agent_kind: string;
  status: string;
  model_name?: string | null;
  stop_reason?: string | null;
  usage_json?: Record<string, unknown>;
  result_json?: Record<string, unknown>;
  started_at?: string | null;
  finished_at?: string | null;
}

export interface ApiKeyCreateRequest {
  name: string;
  role: string;
}

export interface ApiKeyCreatedResponse {
  id: string;
  name: string;
  role: string;
  key_prefix: string;
  created_at?: string | null;
  last_used_at?: string | null;
  revoked_at?: string | null;
  key: string;
}

export interface ApiKeyResponse {
  id: string;
  name: string;
  role: string;
  key_prefix: string;
  created_at?: string | null;
  last_used_at?: string | null;
  revoked_at?: string | null;
}

export interface ApprovalDecisionRequest {
  decided_by: string;
  note?: string | null;
  extension?: Record<string, number> | null;
}

export interface ApprovalResponse {
  id: string;
  document_id: string;
  turn_id?: string | null;
  kind: string;
  status: string;
  payload_json?: Record<string, unknown>;
  policy_id?: string | null;
  decided_by?: string | null;
  decided_at?: string | null;
  decision_note?: string | null;
  created_at?: string | null;
}

export interface Body_bootstrap_uploaded_document_v1_documents_bootstrap_upload_post {
  source_file: string;
}

export interface BookGuideResponse {
  document_id: string;
  markdown: string;
  prompt_guidance: string;
  locked_term_count: number;
  preferred_term_count: number;
  decision_count: number;
}

export interface BootstrapDocumentRequest {
  source_path: string;
}

export interface ChapterMemoryProposalDecisionAuditResponse {
  proposal_id: string;
  decision: "approved" | "rejected";
  actor_type: string;
  actor_id?: string | null;
  note?: string | null;
  created_at: string;
}

export interface ChapterMemoryProposalDecisionRequest {
  actor_name?: string | null;
  note?: string | null;
}

export interface ChapterMemoryProposalDecisionResponse {
  document_id: string;
  chapter_id: string;
  decision: "approved" | "rejected";
  proposal: ChapterMemoryProposalResponse;
  committed_snapshot_id?: string | null;
  committed_snapshot_version?: number | null;
}

export interface ChapterMemoryProposalListResponse {
  document_id: string;
  chapter_id: string;
  status_filter?: "proposed" | "committed" | "rejected" | null;
  proposal_count: number;
  proposals?: ChapterMemoryProposalResponse[];
}

export interface ChapterMemoryProposalQueueSummaryResponse {
  proposal_count: number;
  pending_proposal_count: number;
  counts_by_status?: Record<string, number>;
  latest_proposal_updated_at?: string | null;
  active_snapshot_version?: number | null;
}

export interface ChapterMemoryProposalResponse {
  proposal_id: string;
  packet_id: string;
  translation_run_id: string;
  status: string;
  base_snapshot_version?: number | null;
  committed_snapshot_id?: string | null;
  created_at: string;
  updated_at: string;
  last_decision?: ChapterMemoryProposalDecisionAuditResponse | null;
}

export interface ChapterMemoryProposalSurfaceResponse {
  proposal_count: number;
  pending_proposal_count: number;
  counts_by_status?: Record<string, number>;
  latest_proposal_updated_at?: string | null;
  active_snapshot_version?: number | null;
  pending_proposals?: ChapterMemoryProposalResponse[];
  recent_decisions?: ChapterMemoryProposalDecisionAuditResponse[];
}

export interface ChapterOwnerWorkloadResponse {
  owner_name: string;
  assigned_chapter_count: number;
  immediate_count?: number;
  high_count?: number;
  medium_count?: number;
  breached_count?: number;
  due_soon_count?: number;
  on_track_count?: number;
  owner_ready_count?: number;
  total_open_issue_count?: number;
  total_active_blocking_issue_count?: number;
  oldest_active_issue_at?: string | null;
  latest_issue_at?: string | null;
}

export interface ChapterSummaryResponse {
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  status: string;
  risk_level?: string | null;
  parse_confidence?: number | null;
  structure_flags?: string[];
  sentence_count: number;
  packet_count: number;
  open_issue_count?: number;
  bilingual_export_ready?: boolean;
  latest_bilingual_export_at?: string | null;
  pdf_image_summary?: Record<string, unknown> | null;
  quality_summary?: StoredChapterQualitySummaryResponse | null;
}

export interface ChapterWorklistActionResponse {
  action_id: string;
  issue_id: string;
  issue_type: string;
  action_type: string;
  scope_type: string;
  scope_id?: string | null;
  status: string;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface ChapterWorklistAssignmentClearRequest {
  cleared_by: string;
  note?: string | null;
}

export interface ChapterWorklistAssignmentClearResponse {
  document_id: string;
  chapter_id: string;
  cleared: boolean;
  cleared_by: string;
  note?: string | null;
  cleared_assignment_id: string;
}

export interface ChapterWorklistAssignmentHistoryEntryResponse {
  event_id: string;
  event_type: string;
  owner_name?: string | null;
  performed_by?: string | null;
  note?: string | null;
  created_at: string;
}

export interface ChapterWorklistAssignmentRequest {
  owner_name: string;
  assigned_by: string;
  note?: string | null;
}

export interface ChapterWorklistAssignmentResponse {
  assignment_id: string;
  document_id: string;
  chapter_id: string;
  owner_name: string;
  assigned_by: string;
  note?: string | null;
  assigned_at: string;
  created_at: string;
  updated_at: string;
}

export interface ChapterWorklistIssueResponse {
  issue_id: string;
  issue_type: string;
  root_cause_layer: string;
  severity: string;
  status: string;
  blocking: boolean;
  detector: string;
  suggested_action?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ChapterWorklistTimelineEntryResponse {
  event_id: string;
  source_kind: string;
  event_kind: string;
  created_at: string;
  actor_name?: string | null;
  note?: string | null;
  issue_id?: string | null;
  issue_type?: string | null;
  action_id?: string | null;
  action_type?: string | null;
  scope_type?: string | null;
  scope_id?: string | null;
  status?: string | null;
  proposal_id?: string | null;
  decision?: "approved" | "rejected" | null;
  owner_name?: string | null;
}

export interface CreateDocumentRunRequest {
  document_id: string;
  run_type: DocumentRunType;
  requested_by: string;
  backend?: string | null;
  model_name?: string | null;
  priority?: number;
  resume_from_run_id?: string | null;
  status_detail_json?: Record<string, unknown>;
  budget?: RunBudgetRequest | null;
}

export interface DecisionResponse {
  id: string;
  scope: string;
  scope_id?: string | null;
  key: string;
  value_json?: Record<string, unknown>;
  rationale?: string | null;
  decided_by: string;
  turn_id?: string | null;
  created_at?: string | null;
}

export interface DocumentChapterWorklistDetailResponse {
  document_id: string;
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  chapter_status: string;
  packet_count: number;
  translated_packet_count: number;
  current_issue_count: number;
  current_open_issue_count: number;
  current_triaged_issue_count: number;
  current_active_blocking_issue_count: number;
  assignment?: ChapterWorklistAssignmentResponse | null;
  queue_entry?: IssueChapterQueueEntryResponse | null;
  quality_summary?: StoredChapterQualitySummaryResponse | null;
  issue_family_breakdown?: IssueChapterBreakdownEntryResponse[];
  recent_issues?: ChapterWorklistIssueResponse[];
  recent_actions?: ChapterWorklistActionResponse[];
  assignment_history?: ChapterWorklistAssignmentHistoryEntryResponse[];
  memory_proposals: ChapterMemoryProposalSurfaceResponse;
  timeline?: ChapterWorklistTimelineEntryResponse[];
}

export interface DocumentChapterWorklistResponse {
  document_id: string;
  worklist_count: number;
  filtered_worklist_count: number;
  entry_count: number;
  offset?: number;
  limit?: number | null;
  has_more?: boolean;
  applied_queue_priority_filter?: string | null;
  applied_sla_status_filter?: string | null;
  applied_owner_ready_filter?: boolean | null;
  applied_needs_immediate_attention_filter?: boolean | null;
  applied_assigned_filter?: boolean | null;
  applied_assigned_owner_filter?: string | null;
  queue_priority_counts?: Record<string, number>;
  sla_status_counts?: Record<string, number>;
  immediate_attention_count?: number;
  owner_ready_count?: number;
  assigned_count?: number;
  owner_workload_summary?: ChapterOwnerWorkloadResponse[];
  owner_workload_highlights?: Record<string, ChapterOwnerWorkloadResponse | null>;
  highlights?: Record<string, IssueChapterQueueEntryResponse | null>;
  entries?: IssueChapterQueueEntryResponse[];
}

export interface DocumentContractResponse {
  supported_source_types: string[];
  current_phase: string;
  notes: string[];
}

export interface DocumentExportDashboardResponse {
  document_id: string;
  export_count: number;
  successful_export_count: number;
  filtered_export_count: number;
  record_count: number;
  offset?: number;
  limit?: number | null;
  has_more?: boolean;
  applied_export_type_filter?: string | null;
  applied_status_filter?: string | null;
  latest_export_at?: string | null;
  export_counts_by_type?: Record<string, number>;
  latest_export_ids_by_type?: Record<string, string>;
  total_auto_followup_executed_count?: number;
  translation_usage_summary?: TranslationUsageSummaryResponse | null;
  translation_usage_breakdown?: TranslationUsageBreakdownEntryResponse[];
  translation_usage_timeline?: TranslationUsageTimelineEntryResponse[];
  translation_usage_highlights: TranslationUsageHighlightsResponse;
  issue_hotspots?: IssueHotspotEntryResponse[];
  issue_chapter_pressure?: IssueChapterPressureEntryResponse[];
  issue_chapter_highlights: IssueChapterHighlightsResponse;
  issue_chapter_breakdown?: IssueChapterBreakdownEntryResponse[];
  issue_chapter_heatmap?: IssueChapterHeatmapEntryResponse[];
  issue_chapter_queue?: IssueChapterQueueEntryResponse[];
  issue_activity_timeline?: IssueActivityTimelineEntryResponse[];
  issue_activity_breakdown?: IssueActivityBreakdownEntryResponse[];
  issue_activity_highlights: IssueActivityHighlightsResponse;
  records?: ExportRecordSummaryResponse[];
}

export interface DocumentHistoryBackfillResponse {
  imported_document_count: number;
}

export interface DocumentHistoryEntryResponse {
  document_id: string;
  source_type: string;
  status: string;
  title?: string | null;
  title_src?: string | null;
  title_tgt?: string | null;
  author?: string | null;
  source_path?: string | null;
  created_at: string;
  updated_at: string;
  chapter_count: number;
  sentence_count: number;
  packet_count: number;
  merged_export_ready?: boolean;
  latest_merged_export_at?: string | null;
  chapter_bilingual_export_count?: number;
  latest_run_id?: string | null;
  latest_run_status?: string | null;
  latest_run_current_stage?: string | null;
  latest_run_completed_work_item_count?: number | null;
  latest_run_total_work_item_count?: number | null;
}

export interface DocumentHistoryPageResponse {
  total_count: number;
  record_count: number;
  offset?: number;
  limit?: number | null;
  has_more?: boolean;
  entries?: DocumentHistoryEntryResponse[];
}

export type DocumentRunStatus = "queued" | "running" | "paused" | "draining" | "succeeded" | "succeeded_with_warnings" | "failed" | "cancelled";

export interface DocumentRunSummaryResponse {
  run_id: string;
  document_id: string;
  run_type: string;
  status: string;
  backend?: string | null;
  model_name?: string | null;
  requested_by?: string | null;
  priority: number;
  resume_from_run_id?: string | null;
  stop_reason?: string | null;
  status_detail_json?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  budget?: RunBudgetResponse | null;
  work_items: RunWorkItemSummaryResponse;
  worker_leases: RunLeaseSummaryResponse;
  events: RunEventSummaryResponse;
}

export type DocumentRunType = "bootstrap" | "translate_full" | "translate_targeted" | "review_full" | "export_full" | "repair_targeted";

export type DocumentStatus = "ingested" | "parsed" | "active" | "partially_exported" | "exported" | "failed";

export interface DocumentSummaryResponse {
  document_id: string;
  source_type: string;
  status: string;
  title?: string | null;
  title_src?: string | null;
  title_tgt?: string | null;
  author?: string | null;
  pdf_profile?: Record<string, unknown> | null;
  pdf_page_evidence?: Record<string, unknown> | null;
  pdf_image_summary?: Record<string, unknown> | null;
  chapter_count: number;
  block_count: number;
  sentence_count: number;
  packet_count: number;
  open_issue_count?: number;
  merged_export_ready?: boolean;
  latest_merged_export_at?: string | null;
  chapter_bilingual_export_count?: number;
  latest_run_id?: string | null;
  latest_run_status?: string | null;
  latest_run_current_stage?: string | null;
  latest_run_updated_at?: string | null;
  chapters?: ChapterSummaryResponse[];
}

export interface ExecuteActionResponse {
  action_id: string;
  status: string;
  invalidation_count: number;
  rerun_scope_type: string;
  rerun_scope_ids?: string[];
  followup_executed?: boolean;
  rebuild_applied?: boolean;
  rebuilt_packet_ids?: string[];
  rebuilt_snapshot_ids?: string[];
  rebuilt_snapshots?: RebuiltSnapshotEvidenceResponse[];
  chapter_brief_version?: number | null;
  termbase_version?: number | null;
  entity_snapshot_version?: number | null;
  rerun_packet_ids?: string[];
  rerun_translation_run_ids?: string[];
  issue_resolved?: boolean | null;
  recheck_issue_count?: number | null;
}

export interface ExportAutoFollowupSummaryResponse {
  event_count: number;
  executed_event_count: number;
  stop_event_count: number;
  latest_event_at?: string | null;
  last_stop_reason?: string | null;
}

export interface ExportDetailResponse {
  document_id: string;
  export_id: string;
  export_type: string;
  status: string;
  file_path: string;
  manifest_path?: string | null;
  chapter_id?: string | null;
  sentence_count: number;
  target_segment_count: number;
  created_at: string;
  updated_at: string;
  translation_usage_summary?: TranslationUsageSummaryResponse | null;
  translation_usage_breakdown?: TranslationUsageBreakdownEntryResponse[];
  translation_usage_timeline?: TranslationUsageTimelineEntryResponse[];
  translation_usage_highlights?: TranslationUsageHighlightsResponse | null;
  issue_status_summary?: ExportIssueStatusSummaryResponse | null;
  export_auto_followup_summary?: ExportAutoFollowupSummaryResponse | null;
  export_time_misalignment_counts?: ExportMisalignmentCountSummaryResponse | null;
  version_evidence_summary: ExportVersionEvidenceSummaryResponse;
}

export interface ExportDocumentRequest {
  export_type: "review_package" | "bilingual_html" | "merged_html" | "merged_markdown" | "rebuilt_epub" | "rebuilt_pdf" | "zh_epub";
  auto_execute_followup_on_gate?: boolean;
  max_auto_followup_attempts?: number;
}

export interface ExportIssueStatusSummaryResponse {
  issue_count: number;
  open_issue_count: number;
  resolved_issue_count: number;
  blocking_issue_count: number;
}

export interface ExportMisalignmentCountSummaryResponse {
  missing_target_sentence_count: number;
  inactive_only_sentence_count: number;
  orphan_target_segment_count: number;
  inactive_target_segment_with_edges_count: number;
}

export interface ExportRecordSummaryResponse {
  export_id: string;
  export_type: string;
  status: string;
  file_path: string;
  manifest_path?: string | null;
  chapter_id?: string | null;
  chapter_summary_version?: number | null;
  created_at: string;
  updated_at: string;
  translation_usage_summary?: TranslationUsageSummaryResponse | null;
  translation_usage_breakdown?: TranslationUsageBreakdownEntryResponse[];
  translation_usage_timeline?: TranslationUsageTimelineEntryResponse[];
  translation_usage_highlights?: TranslationUsageHighlightsResponse | null;
  export_auto_followup_summary?: ExportAutoFollowupSummaryResponse | null;
  export_time_misalignment_counts?: ExportMisalignmentCountSummaryResponse | null;
}

export type ExportStatus = "running" | "succeeded" | "failed";

export type ExportType = "bilingual_html" | "merged_html" | "merged_markdown" | "rebuilt_epub" | "rebuilt_pdf" | "zh_epub" | "review_package";

export interface ExportVersionEvidenceSummaryResponse {
  document_parser_version?: number | null;
  document_segmentation_version?: number | null;
  book_profile_version?: number | null;
  chapter_summary_version?: number | null;
  active_snapshot_versions?: Record<string, number>;
}

export interface ExportVersionHistoryResponse {
  document_id: string;
  export_id: string;
  export_type: string;
  current_version: number;
  versions?: ExportVersionResponse[];
}

export interface ExportVersionResponse {
  version: number;
  file_path: string;
  manifest_path?: string | null;
  content_sha256?: string | null;
  byte_count?: number | null;
  created_at?: string | null;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthResponse {
  status: string;
}

export interface IssueActionResponse {
  id: string;
  issue_id: string;
  action_type: string;
  scope_type: string;
  scope_id?: string | null;
  status: string;
  reason_json?: Record<string, unknown>;
  created_by: string;
  updated_at?: string | null;
}

export interface IssueActivityBreakdownEntryResponse {
  issue_type: string;
  root_cause_layer: string;
  issue_count: number;
  open_issue_count: number;
  blocking_issue_count: number;
  latest_seen_at?: string | null;
  timeline?: IssueActivityTimelineEntryResponse[];
}

export interface IssueActivityHighlightsResponse {
  top_regressing_entry?: IssueActivityBreakdownEntryResponse | null;
  top_resolving_entry?: IssueActivityBreakdownEntryResponse | null;
  top_blocking_entry?: IssueActivityBreakdownEntryResponse | null;
}

export interface IssueActivityTimelineEntryResponse {
  bucket_start: string;
  bucket_granularity: string;
  created_issue_count: number;
  resolved_issue_count: number;
  wontfix_issue_count: number;
  blocking_created_issue_count: number;
  net_issue_delta: number;
  estimated_open_issue_count: number;
}

export interface IssueChapterBreakdownEntryResponse {
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  chapter_status: string;
  issue_type: string;
  root_cause_layer: string;
  issue_count: number;
  open_issue_count: number;
  triaged_issue_count: number;
  resolved_issue_count: number;
  blocking_issue_count: number;
  active_blocking_issue_count: number;
  latest_seen_at?: string | null;
}

export interface IssueChapterHeatmapEntryResponse {
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  chapter_status: string;
  issue_count: number;
  open_issue_count: number;
  triaged_issue_count: number;
  resolved_issue_count: number;
  blocking_issue_count: number;
  active_blocking_issue_count: number;
  issue_family_count: number;
  dominant_issue_type?: string | null;
  dominant_root_cause_layer?: string | null;
  dominant_issue_count: number;
  latest_issue_at?: string | null;
  heat_score: number;
  heat_level: string;
}

export interface IssueChapterHighlightsResponse {
  top_open_chapter?: IssueChapterPressureEntryResponse | null;
  top_blocking_chapter?: IssueChapterPressureEntryResponse | null;
  top_resolved_chapter?: IssueChapterPressureEntryResponse | null;
}

export interface IssueChapterPressureEntryResponse {
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  chapter_status: string;
  issue_count: number;
  open_issue_count: number;
  triaged_issue_count: number;
  resolved_issue_count: number;
  blocking_issue_count: number;
  latest_issue_at?: string | null;
}

export interface IssueChapterQueueEntryResponse {
  chapter_id: string;
  ordinal: number;
  title_src?: string | null;
  chapter_status: string;
  issue_count: number;
  open_issue_count: number;
  triaged_issue_count: number;
  blocking_issue_count: number;
  active_blocking_issue_count: number;
  issue_family_count: number;
  dominant_issue_type?: string | null;
  dominant_root_cause_layer?: string | null;
  dominant_issue_count: number;
  latest_issue_at?: string | null;
  heat_score: number;
  heat_level: string;
  queue_rank: number;
  queue_priority: string;
  queue_driver: string;
  needs_immediate_attention: boolean;
  oldest_active_issue_at?: string | null;
  age_hours?: number | null;
  age_bucket: string;
  sla_target_hours?: number | null;
  sla_status: string;
  owner_ready: boolean;
  owner_ready_reason: string;
  is_assigned?: boolean;
  assigned_owner_name?: string | null;
  assigned_at?: string | null;
  latest_activity_bucket_start?: string | null;
  latest_created_issue_count: number;
  latest_resolved_issue_count: number;
  latest_net_issue_delta: number;
  regression_hint: string;
  flapping_hint: boolean;
  memory_proposals: ChapterMemoryProposalQueueSummaryResponse;
}

export interface IssueDecisionRequest {
  actor_id: string;
  note?: string | null;
}

export interface IssueDetailResponse {
  issue: IssueResponse;
  events?: IssueEventResponse[];
  actions?: IssueActionResponse[];
  source_text?: string | null;
  target_text?: string | null;
  chapter_title?: string | null;
}

export interface IssueEventResponse {
  id: string;
  issue_id: string;
  version: number;
  kind: string;
  from_status?: string | null;
  to_status: string;
  actor_kind: string;
  actor_id?: string | null;
  note?: string | null;
  evidence_json?: Record<string, unknown>;
  created_at?: string | null;
}

export interface IssueHotspotEntryResponse {
  issue_type: string;
  root_cause_layer: string;
  issue_count: number;
  open_issue_count: number;
  triaged_issue_count: number;
  resolved_issue_count: number;
  wontfix_issue_count: number;
  blocking_issue_count: number;
  chapter_count: number;
  latest_seen_at?: string | null;
}

export interface IssueListResponse {
  document_id: string;
  total_count: number;
  offset: number;
  limit: number;
  has_more: boolean;
  entries?: IssueResponse[];
}

export interface IssueResponse {
  id: string;
  document_id: string;
  chapter_id?: string | null;
  block_id?: string | null;
  sentence_id?: string | null;
  packet_id?: string | null;
  issue_type: string;
  root_cause_layer: string;
  severity: string;
  blocking: boolean;
  detector: string;
  confidence?: number | null;
  status: string;
  version: number;
  reopen_count: number;
  suggested_action?: string | null;
  resolution_note?: string | null;
  decided_by?: string | null;
  decided_at?: string | null;
  evidence_json?: Record<string, unknown>;
  created_at?: string | null;
  updated_at?: string | null;
  last_seen_at?: string | null;
}

export type MemoryProposalStatus = "proposed" | "committed" | "rejected";

export interface MetaResponse {
  app_name: string;
  version: string;
  environment: string;
  api_prefix: string;
  docs_path: string;
}

export interface OrgBudgetResponse {
  org_id: string;
  org_name: string;
  monthly_budget_usd: number | null;
  spent_usd: number;
  remaining_usd?: number | null;
  exhausted: boolean;
  period_start: string;
}

export interface OrgBudgetUpdate {
  monthly_budget_usd?: number | null;
}

export interface ProviderCredentialCreate {
  name: string;
  provider_kind: ProviderKind;
  model_name: string;
  base_url: string;
  streaming?: boolean;
  max_output_tokens?: number;
  timeout_seconds?: number;
  max_retries?: number;
  retry_backoff_seconds?: number;
  api_key?: string | null;
  activate?: boolean;
}

export interface ProviderCredentialRead {
  name: string;
  provider_kind: ProviderKind;
  model_name: string;
  base_url: string;
  streaming?: boolean;
  max_output_tokens?: number;
  timeout_seconds?: number;
  max_retries?: number;
  retry_backoff_seconds?: number;
  id: string;
  is_active: boolean;
  api_key_preview?: string | null;
  shared?: boolean;
  last_test_status: ProviderTestStatus;
  last_test_at?: string | null;
  last_test_message?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProviderCredentialUpdate {
  name?: string | null;
  provider_kind?: ProviderKind | null;
  model_name?: string | null;
  base_url?: string | null;
  api_key?: string | null;
  streaming?: boolean | null;
  max_output_tokens?: number | null;
  timeout_seconds?: number | null;
  max_retries?: number | null;
  retry_backoff_seconds?: number | null;
}

export type ProviderKind = "openai_compatible" | "echo";

export interface ProviderTestResult {
  status: ProviderTestStatus;
  message?: string | null;
  elapsed_ms?: number | null;
  sample_output?: string | null;
}

export type ProviderTestStatus = "unknown" | "ok" | "failed";

export interface RebuiltSnapshotEvidenceResponse {
  snapshot_id: string;
  snapshot_type: string;
  version: number;
}

export interface RecoverySkillResponse {
  name: string;
  title: string;
  description: string;
  passes?: string[];
  default_enabled: boolean;
  enabled: boolean;
}

export interface RecoverySkillsResponse {
  document_id: string;
  applies_to: string;
  skills?: RecoverySkillResponse[];
}

export interface RecoverySkillsUpdateRequest {
  skills?: Record<string, boolean>;
}

export interface RunAuditEventPageResponse {
  run_id: string;
  event_count: number;
  record_count: number;
  offset: number;
  limit?: number | null;
  has_more?: boolean;
  entries?: RunAuditEventResponse[];
}

export interface RunAuditEventResponse {
  event_id: string;
  run_id: string;
  work_item_id?: string | null;
  event_type: string;
  actor_type: string;
  actor_id?: string | null;
  payload_json?: Record<string, unknown>;
  created_at: string;
}

export interface RunBudgetRequest {
  max_wall_clock_seconds?: number | null;
  max_no_progress_seconds?: number | null;
  max_total_cost_usd?: number | null;
  max_total_token_in?: number | null;
  max_total_token_out?: number | null;
  max_retry_count_per_work_item?: number | null;
  max_consecutive_failures?: number | null;
  max_parallel_workers?: number | null;
  max_parallel_requests_per_provider?: number | null;
  max_auto_followup_attempts?: number | null;
}

export interface RunBudgetResponse {
  max_wall_clock_seconds?: number | null;
  max_no_progress_seconds?: number | null;
  max_total_cost_usd?: number | null;
  max_total_token_in?: number | null;
  max_total_token_out?: number | null;
  max_retry_count_per_work_item?: number | null;
  max_consecutive_failures?: number | null;
  max_parallel_workers?: number | null;
  max_parallel_requests_per_provider?: number | null;
  max_auto_followup_attempts?: number | null;
}

export interface RunControlRequest {
  actor_id: string;
  note?: string | null;
  detail_json?: Record<string, unknown>;
}

export interface RunEventSummaryResponse {
  event_count: number;
  latest_event_at?: string | null;
}

export interface RunLeaseSummaryResponse {
  total_count: number;
  status_counts?: Record<string, number>;
  latest_heartbeat_at?: string | null;
}

export interface RunLineageNodeResponse {
  run_id: string;
  document_id: string;
  run_type: string;
  status: string;
  resume_from_run_id?: string | null;
  requested_by?: string | null;
  stop_reason?: string | null;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  finished_at?: string | null;
}

export interface RunLineageResponse {
  focus_run_id: string;
  root_run_id: string;
  document_id: string;
  node_count: number;
  nodes?: RunLineageNodeResponse[];
}

export interface RunWorkItemSummaryResponse {
  total_count: number;
  status_counts?: Record<string, number>;
  stage_counts?: Record<string, number>;
}

export type SourceType = "epub" | "pdf_text" | "pdf_scan" | "pdf_mixed";

export interface StoredChapterQualitySummaryResponse {
  issue_count: number;
  action_count: number;
  resolved_issue_count: number;
  coverage_ok: boolean;
  alignment_ok: boolean;
  term_ok: boolean;
  format_ok: boolean;
  blocking_issue_count: number;
  low_confidence_count: number;
  format_pollution_count: number;
}

export interface StructureEditListResponse {
  document_id: string;
  edits: StructureEditResponse[];
}

export interface StructureEditRequest {
  kind: "relabel_block" | "merge_blocks" | "link_caption";
  reason: string;
  block_id?: string | null;
  block_type?: string | null;
  heading_level?: number | null;
  first_block_id?: string | null;
  second_block_id?: string | null;
  caption_block_id?: string | null;
  artifact_block_id?: string | null;
}

export interface StructureEditResponse {
  edit_id: string;
  kind: string;
  status: string;
  block_ids?: string[];
  args?: Record<string, unknown>;
  actor_id: string;
  reason?: string | null;
  turn_id?: string | null;
  replay_of_edit_id?: string | null;
  parse_revision_version?: number | null;
  retranslate_packet_count?: number;
  created_at?: string | null;
}

export interface StructureRefreshResponse {
  document_id: string;
  source_type: string;
  refreshed_chapter_count: number;
  refreshed_block_count: number;
  parse_revision_version?: number | null;
  retired_sentence_count?: number;
  created_sentence_count?: number;
  carried_ratio?: number | null;
  retranslate_packet_count?: number;
}

export interface TranslateDocumentRequest {
  packet_ids?: string[];
}

export interface TranslationUsageBreakdownEntryResponse {
  model_name: string;
  worker_name?: string | null;
  provider?: string | null;
  run_count: number;
  succeeded_run_count: number;
  total_token_in: number;
  total_token_out: number;
  total_cost_usd: number;
  total_latency_ms: number;
  avg_latency_ms?: number | null;
  latest_run_at?: string | null;
}

export interface TranslationUsageHighlightsResponse {
  top_cost_entry?: TranslationUsageBreakdownEntryResponse | null;
  top_latency_entry?: TranslationUsageBreakdownEntryResponse | null;
  top_volume_entry?: TranslationUsageBreakdownEntryResponse | null;
}

export interface TranslationUsageSummaryResponse {
  run_count: number;
  succeeded_run_count: number;
  total_token_in: number;
  total_token_out: number;
  total_cost_usd: number;
  total_latency_ms: number;
  avg_latency_ms?: number | null;
  latest_run_at?: string | null;
}

export interface TranslationUsageTimelineEntryResponse {
  bucket_start: string;
  bucket_granularity: string;
  run_count: number;
  succeeded_run_count: number;
  total_token_in: number;
  total_token_out: number;
  total_cost_usd: number;
  total_latency_ms: number;
  avg_latency_ms?: number | null;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
